services:
  - type: web
    name: smart-simhastha-2028
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python seed.py && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: MONGO_URI
        sync: false
